### ISSUE TITLE
[Card v2]: Epic

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#10100]
#### Design Tasks
- [ ] Default card exploration
- [ ] Default card specs
- [ ] Default card website v2 updates
- [ ] Default card Figma v2 updates

#### Dev Tasks
TBD
