### ISSUE TITLE
[Card – Pictogram] Pictogram placement and body reveal

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-ibm-dotcom#10127]
We need to add website guidance to encourage using the bottom alignment (pattern guidance). The option to toggle between top and bottom alignment will stay in v2.

We should also review the body copy reveal on hover to see if there are accessibility or interaction concerns. Add border to bring in line with `card` updates for v2.

**Guidance updates**
- [x] Update website language to encourage bottom alignment.
- [x] Review website changes with Jeannie, Olivia, and Rich
- [x] Deploy website guidance changes – [#1555](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/pull/1555)
- [x] Add description in Figma kit to encourage bottom alignment (make the default)
- [x] Add dev story to update default to `bottom alignment`, if needed – #10195 

**Body copy reveal**
- [x] Review body copy reveal
- [x] Review body copy reveal with Jeannie, Olivia, and Rich
- [x] Update **[design specs](https://www.figma.com/file/oip4K9G1z0v7tLNBbDZzdr/Card-specs?t=RmkvV2f0XrgzRKLv-6)** 
- [x] Add v2 dev story for hover reveal change – #10199 
- [x] Add Figma kit story – #10201

**Comment by RichKummer** [comment]
[Discussion with a11y notes](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/8101

![Image](https://user-images.githubusercontent.com/15643582/222233914-ac52e967-1dbf-4c46-95d8-f7de0222a473.png)

)

**Comment by RichKummer** [comment]
## Design crit 03/02/23
- Gower's feedback for the hover reveal was that users may miss the title when focusing. Someone using a zoom feature in their browser may also miss the title as it animates away while the cursor is passing over the card.
- In a group, the hover might be chaotic with some content appearing/disappearing.
- Body copy should be optional, and resize the button down to an aspect ratio. 
- We should remove the hover reveal, and instead display all content without hiding behind a hover. This makes the `card – pictogram` more accessible and ensure they can see the most important takeaways in a single view.
