### ISSUE TITLE
[Feature section] Rename and update specs

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-ibm-dotcom#10136]
The `feature section` component uses "section" in the name, but does not align with the `content section` component. We should consider a new name to differentiate to avoid confusion. ~We should also explore a 12-column option as an additional variant.~

**Tasks**
- [x] Brainstorm new names for `feature section`
- [ ] Update card to use outlined stroke
- [ ] Update to `8px` spacing between heading and eyebrow, similar to `feature card` updates
- [ ] Create a light variant 
- [ ] Update type and color tokens to v11

**Question:** Do we need a light theme variant similar to the v2 updates to `feature card`?

**[Design specs in Sketch](https://ibm.ent.box.com/folder/137684054266?s=pffea4dd5aug4m3v6za7ewjd1metosg8)**

- [ ] Review with Jeannie, Olivia, and Rich
- [ ] Update design specs
- [ ] Create Figma kit story
- [ ] Create website update story
- [ ] Create dev story

**Comment by oliviaflory** [comment]
### Decision:
We will not rename and leave as feature section

**Comment by oliviaflory** [comment]
Design specs finished
