### ISSUE TITLE
[Card in card] interaction exploration

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-ibm-dotcom#10134]
For v2 we need to review the clickable interactive area for `card in card` across variants.

**Resources**
[V1 Design specs](https://www.figma.com/file/Y3Hy8ULHJH4t8XzT29mktJ/UI-component--card-in- card--visual-specs-v1.1?node-id=1%3A6490&t=LFMqHfOdMV80g5gQ-1)

[Card default]()

**Tasks**
- [x] Review clickable/interactive area for `card in card`
- [x] Border: around image or around inset card
- [x] play button: transition to filled play icon & review play button overlay logic

**Acceptance criteria**
- [x] Review explorations both with Jeannie, Olivia, and Rich
- [x] Create design spec issue
- [ ] Create website guidance update story
- [ ] Create Figma kit update story

**Comment by oliviaflory** [comment]
- border around media and inner card
- use focus + inner focus
- include overlay on hover
- no play icon overlay on top of media, play icon will appear in the card
