### ISSUE TITLE
Create spec standard for Figma

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#10254]
### Create a standard for specing components

- We need a consistent way to spec our components now that we have switched to Figma.
   - We each have a slightly different style / approach to our specs
- We previously had the Sketch spec template that Shixie created
   - There is a Figma version we could look at, but it's missing the teal padding we used to use.
- Figma guild has a template file we could reference, 
   - We currently use the Cover from the Figma guild
   - The "Final spec" page of their document seems tailored to a whole project or product vs individual component needs.

#### Things to consider
- What should be in the file
-- I like Carbon's structure
-- About (Cover & Updates)
-- Process
-- Specs
- Measurements
-- How to handle the spacing tokens and padding (lost from Sketch)
- Style (Color tokens, type tokens)
-- Do we show all themes or is white enough
- Breakpoints
- UI vs Layout components

### Tasks
- [ ] Rich & Olivia Brainstorm 
- [ ] Establish a checklist of requirements
- [ ] Create template (could roll to another issue)
- [ ] Review with team

**Comment by oliviaflory** [comment]
Done, could potentially make the file into a template in the future
