### ISSUE TITLE
[Feature card] Aspect ratio follow-on

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-ibm-dotcom#10260]
Follow-on to #10137.
Updated spacing between eyebrow and heading to `8px` per feedback in Design Office Hours 03-29-23

- [x] Discuss options with Mike/Jeannie/Olivia
- [x] Update design specs, including v2 – [Updated design specs](https://www.figma.com/file/DmgpvpEV6m4eJNMgKOLPmy/Feature-card-v2?node-id=0%3A1&t=sULZh5rvMnbw2uqD-1)
- [x]  Create Figma kit story – #10299 
- [x]  Create website update story – #10296 
- [x]  Create dev story – #10306

**Comment by RichKummer** [comment]
## Mike/Olivia/Jeannie review 03-29-23

### Feature card @md

- Use 2:1, same as `@lg`
- Consider swap to `body-02` (14px)
    - Maintains more of the scale of header + text
    - We can use adaptive text here
- For truncation, needs to account for heading AND body copy.
- Need guidance for weighing more in heading or body copy.
    - Avoid using product names in body copy
    - Is there a way in AEM to figure out the right amount of copy.

### Feature card @lg

- Move to `heading-03` `@lg`
- Guidance should be to use something else if the content is too much

**Comment by RichKummer** [comment]
## Team Huddle 04-04-23
### Feature card – large `@lg`
- Implement `2:1` aspect ratio with truncation on body copy.
- Clear guidance around truncation:
    - Body copy is secondary, cannot include product names.
    - If there’s too much content, use a `content` component.
