### ISSUE TITLE
[Card in card]: v2 Epic

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#10292]
### User story

Epic to track updates to Card in card for v2

### Additional information

```[tasklist]
### Design
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10134
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10276
- [ ] Website
- [ ] Figma
```

```[tasklist]
### Dev
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10384
- [ ] Visual QA
```

**Comment by oliviaflory** [comment]
closing epic in favor of new organization strategy
