### ISSUE TITLE
[Figma] Card – default

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#10324]
### Updates to Card – default

[Spec file](https://www.figma.com/file/oip4K9G1z0v7tLNBbDZzdr/Card-specs-v2?node-id=23%3A3280&t=4fB58G580bJcIuip-1)

### Issues for reference
- [Exploration](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/9935)
- [Spec](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10175)

### Tasks
- [ ] Update type tokens to v11
- [ ] Update color tokens to v11
- [ ] Add border to default tile
- [ ] Option to change icon / CTA type
- [ ] Video variant
   - [ ] Icon cannot be changed
   - [ ] time field is added
