### ISSUE TITLE
[Card – pictogram] v2 Epic

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#10332]
## Epic to track Card pictogram changes for v2

```[tasklist]
### Design
- [ ] Spec story
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/issues/1566
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10459
```

``` [tasklist]
### Dev
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10199
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10195
```

**Comment by oliviaflory** [comment]
closing epic in favor of new organization strategy
