### ISSUE TITLE
[CTA] web component

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#10359]
### User story
We will be deprecating the CTA component in v2

### Additional information
The CTA component is redundant right now, it pulls from other components (link, link with icon, card, card link, button group). 
We plan to deprecate the CTA component and direct users to use the components listed above directly.

### Tasks
- [ ] See if there is a way to automate the conversions from "CTA" to the other components
- [ ] Add deprecation notice to CTA component
- [ ] Remove from v2 storybook
- [ ] Identify breaking changes and migration guidance?

### Acceptance criteria
