### ISSUE TITLE
[Content item] v2 Epic

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#10361]
### Epic to track Content item updates for Carbon for IBM.com v2

```[tasklist]
### Design
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10360
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10255
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10461
- [ ] Website
```

```[tasklist]
### Dev
- [ ] Web component
- [ ] QA
```

**Comment by oliviaflory** [comment]
closing epic in favor of new organization strategy
