### ISSUE TITLE
[Content item] v2 design exploration

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#10360]
### User story

We are considering merging content item with pictogram item and want to explore if we want to allow horizontal layouts for the additional variants we are adding to Content item.

### Tasks
- Reference the existing [Pictogram item spec](https://www.figma.com/file/11eKMUiXOKyPdosqYM8UM2/Layout-component--pictogram-item--visual-specs--1.0.0?node-id=0%3A1&t=ngO8AqYddxV9dxWh-1)
- Reference the additional variants in the [Figma file](https://www.figma.com/file/7Ag5FbE2NziWF2Ed8UmWmg/Content-item-explo?node-id=74%3A7171&t=wSPs068J6DhqtnZS-1)
- Image
   - 1:1 ratio or allow others?
   - 80px  square, 3 columns or 4?
   - Video? probably not good for playing inline, how would the launch work?
- Logo?
   - Could be useful for app icon
- Statistic
   - What would be the width limitation

### Acceptance criteria
- [x] Review with design team
- [x] Decide which variants are moving forward
- [x] Write spec story – #10415

**Comment by RichKummer** [comment]
**[Figma design exploration](https://www.figma.com/file/7Ag5FbE2NziWF2Ed8UmWmg/Content-item-explo?node-id=202%3A9380&t=dhCWQA4ZyjD4f9HQ-1)**

**Comment by RichKummer** [comment]
## Design review feedback
## Pictogram/content item

- General/all variants
    - Copy can be off the grid if locked up with a pictogram
- Pictogram
    - `80px` pictogram might be too large, **use `64px` with 32px spacing**
- Images
    - Allow `1:1` and `3:2` aspect ratio.
    - For mobile, use full-width images for each aspect ratio.
        - For pictogram or app icons, keep the same size across breakpoints. There should be different rules across media types.
- Logos – use `80px` or `64px` like Pictogram?
- Stats
    - Should we offer this at all? ******************************************************************************No, we will not offer it for horizontal******************************************************************************
- Responsive resizing:
    - Pictogram and app icon do not resize `@sm`
    - Image resizes to full-width on `@sm`

**Comment by RichKummer** [comment]
## Horizontal / Vertical breakdown



Content item variant | Horizontal | Vertical | Notes
-- | -- | -- | --
Pictogram | Yes ✅ | Yes ✅ | Pictogram size is adjusted to 64px foir both vertical and horizontal
Image | Yes ✅ | Yes ✅ | Available aspect ratios in vertical are 1:1 and 3:2
App icon (logo) | Yes ✅ | Yes ✅ | App icons use 64px size only
Statistics | Yes ✅ | No ❌ | Not available for vertical orientation
