### ISSUE TITLE
[Feature card] v2 Epic

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#10381]
### Epic to track Feature card v2 updates

```[tasklist]
### Design
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/9922
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10137
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10260
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/9009
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10299
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/issues/1556
```

```[tasklist]
### Dev
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10306
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10072
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10073
- [ ] QA
```

**Comment by oliviaflory** [comment]
closing epic in favor of new organization strategy
