### ISSUE TITLE
[Card – static] v2 Epic

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#10382]
### Epic to track Card – static updates for v2

```[tasklist]
### Design
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10128
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10245
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/issues/1565
```

```[tasklist]
### Dev
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10244
- [ ] QA
```

**Comment by oliviaflory** [comment]
closing epic in favor of new organization strategy
