### ISSUE TITLE
[Content Section]: update `content-section` to v2 design specs

### ISSUE THREAD

**Issue by kennylam** [carbon-design-system/carbon-for-ibm-dotcom#10454]
This issue tracks required tasks for the new `content-section` component in v2.

```[tasklist]
### Tasks
- [ ] `content-section` should accept all `content-block|group|item` as children
- [ ] define permitted content types for left column
- [ ] ensure spacing is consistent for top/bottom of section
```
