### ISSUE TITLE
[ToC] v2 Epic

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#10465]
# Epic to track changes to Table of Contents in v2

We need to update the keyboard controls for the default/vertical ToC
We need to update the overall design for the horizontal ToC

### Review notes
[4/25](https://ibm.ent.box.com/notes/1199027727421)

## Default / Vertical

```[tasklist]
### Design
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10149
- [ ] #10467 
- [ ] Website
- [ ] Figma
```

```[tasklist]
### Dev
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10514
- [ ] QA
```

## Horizontal

```[tasklist]
### Design
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10323
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10560
- [ ] Website
- [ ] Figma
```

```[tasklist]
### Dev
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10512
- [ ] QA
```

**Comment by oliviaflory** [comment]
Closing epic in favor of new organization strategy
