### ISSUE TITLE
[ToC vertical] Design specs

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#10467]
### Update keyboard interactions

Update the keyboard interaction of the ToC to follow recommendations from the Accessibility guild

**General**

- The ToC is primarily there to orient the user where they are on the page
- What is the expected mouse & keyboard behavior for Table of Contents
- Would be easier if the ToC was not interactive

**Vertical**
Not a failure as-is

**Suggestion:**
- Change the Vertical toc to a navigation region
- Lets you jump back to ToC
- Focus would be on the item when you jump back into the region.
- Execute and focus is shifted into section,
- User can jump back into the navigation region.

### Tasks
- [x] Use the accessibility design kit to document the expected keyboard interaction
- [x] Migrate specs to Figma
- [x] Update vertical design specs with v11 color tokens
- [x] Update design specs with v11 type styles

### Acceptance criteria
- [x] Uses Figma spec guidelines
- [x] Review with Michael Gower / Devs in accessibility guild [#10322](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10322)
- [x] Review with design team
- [x] Talk with Devs
