### ISSUE TITLE
[Link list] v2 specs

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#10531]
### Decisions:
- Align hover states within link list components
   - Remove background hover change
   - All text underline on hover
   - Default & section focus state will remain around the entire area vs just the text

### Tasks
- [x] Create specs in Figma
- [x] Update to v11 type tokens & colors
- [ ] Update website issue
- [ ] Update dev issue
- [ ] Update figma issue
