### ISSUE TITLE
[Callout quote] v2 Epic

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#10542]
```[tasklist]
### Design
- [ ] [ ] Callout quote v2 design specs
- [ ] Website
- [ ] [ ] Figma
```

```[tasklist]
### Dev
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/9621
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/9615
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10050
- [ ] [ ] v2 WC
- [ ] [ ] QA
```

**Comment by oliviaflory** [comment]
Closing epic in favor of new organization tactic
