### ISSUE TITLE
[Carbon web components]: update component CDN to use global styles

### ISSUE THREAD

**Issue by kennylam** [carbon-design-system/carbon-for-ibm-dotcom#10557]
Current component CDN files all include global styles from the Carbon Design System, such as layout, grid, resets, etc. This adds a substantial amount of redundant code to any project using the CDN files. Ideally all global styles should live in their own respective files, to be included wherever needed. This will considerably decrease load times of pages.

```[tasklist]
### Tasks
- [ ] [carbon web components]: place global styles for CDN in respective stylesheets
- [ ] [docs]: update CDN documentation to include any new stylesheets
- [ ] [stackblitz]: create example using new CDN files
```

**Comment by andy-blum** [comment]
Anecdotally, this should be a huge boost for AEM. A quick hack-and-slash removing all CSS from our bundled web components takes the unminified version of the file down from 12.4mb to 2.8mb
