### ISSUE TITLE
[Storybook]: update all `@carbon/ibm-dotcom-web-components` stories to use controls

### ISSUE THREAD

**Issue by kennylam** [carbon-design-system/carbon-for-ibm-dotcom#10578]
This epic tracks the effort to update Storybook stories to use controls instead of knobs. `content-block|group|item-*` components excluded for now until v2 design audit work is complete.

### Web components

```[tasklist]
### Tasks
- [ ] background-media
- [ ] button-group
- [ ] callout-quote
- [ ] callout-with-media
- [ ] card-group
- [ ] card-in-card
- [ ] card-link
- [ ] card-section-carousel
- [ ] card-section-offset
- [ ] card-section-simple
- [ ] card
- [ ] carousel
- [ ] cta-block
- [ ] cta-section
- [ ] cta
- [ ] dotcom-shell
- [ ] expressive-modal
- [ ] feature-card
- [ ] feature-section
- [ ] filter-panel
- [ ] footer
- [ ] image
- [ ] layout
- [ ] lead-space-block
- [ ] lead-space-search
- [ ] lead-space
- [ ] leaving-ibm
- [ ] lightbox-media-viewer
- [ ] link-list-section
- [ ] link-list
- [ ] link-with-icon
- [ ] locale-modal
- [ ] logo-grid
- [ ] masthead
- [ ] notice-choice
- [ ] pictogram-item
- [ ] quote
- [ ] scroll-animations
- [ ] search-with-typeahead
- [ ] structured-list
- [ ] table-of-contents
- [ ] tabs-extended - with media
- [ ] tabs-extended
- [ ] tag-group
- [ ] tag-link
- [ ] universal-banner
- [ ] video-player
```
