### ISSUE TITLE
[Web components]: optimize DOM node counts

### ISSUE THREAD

**Issue by kennylam** [carbon-design-system/carbon-for-ibm-dotcom#10666]
JIRA: https://jsw.ibm.com/browse/ADCMS-3580

This issue tracks the effort to optimize components in the `@carbon/ibmdotcom-web-components` package. Current solutions include reducing the amount of nodes in components (duplicates, empty nodes, etc) and lazy loading content, such as only loading content visible in certain viewport sizes.

Hidden content can be added or removed from the DOM as needed, drastically reducing the number of rendered nodes. Additionally, tests can be done to minify template literals with dependencies such as [this](https://www.npmjs.com/package/rollup-plugin-minify-html-literals).

**Note:** as so many components are comprised of other components, some optimizations should be done in the individual sub-components, e.g. `Content block media - with link list`.

This list is not final. More components will be added as needed.

Full list [here](https://ibm.ent.box.com/notes/1249297332844).

```[tasklist]
### Component (listed in order of highest node count)
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10667
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10657
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10656
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10618
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10668
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10669
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10670
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10671
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10672
```
