### ISSUE TITLE
[Comms] v2 Epic

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#10717]
## Epic to track all communications needed leading up to the Carbon for IBM.com v2 release.

```[tasklist]
### Info sessions
- [ ] [Info session 3] presentation prep – date TBD
- [ ] [Info session 4] presentation prep – date TBD
```

```[tasklist]
### Medium posts
- [x] [Medium post] C4IBMv2 beta
- [x] [Medium post] C4IBMv2 release candidate
- [x] [Medium post] C4IBMv2 final release
- [ ] [Medium post] Spacing challenge (Rich)
```

```[tasklist]
### Slack announcements
- [ ] Draft task
```
