### ISSUE TITLE
[Migration] v2 Epic

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#10716]
## Epic to track all issues related to migration

```[tasklist]
### Migration documentation CWC v2
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10733
- [ ] Update Storybook docs examples
- [ ] Update new, removed, or changed components and component names and any path changes
```

```[tasklist]
### Migration documentation Carbon for IBM.com
- [ ] Create migration guide for C4IBM V1 -> V2 WC
- [ ] Create migration guide for React -> React Wrappers
- [ ] [Website] Add migration docs to website
- [ ] Change components in NextJS Template to use React Wrappers instead
```
