### ISSUE TITLE
[Components] `@carbon/ibmdotcom-web-components` Development v2 Epic

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#10715]
## Epic to track all component work for V2
> [!note]
> all work should be done in the `feat/carbon-for-ibm-dotcom-v2` branch

This epic tracks the work to update all components in `@carbon/ibmdotcom-web-components`. Component styles and markup need to be updated as all upstream Carbon dependencies now use Carbon v11. As components in `@carbon/web-components` - an upstream dependency - have been upgraded to v11, the markup in many components in this package must be updated as well.

Issues with the `v2 design change` label have specific design requirements and may also introduce breaking changes. These issues should include updated design specs, component API changes, and may require working with the design team during implementation.

**[Component dependency map (Box Canvas)](https://ibm.box.com/s/n6av12wl31tny8vaf77dz4jrl4skzcn7)**

### Acceptance criteria
For all components, some basic acceptance criteria should be observed when working on them:
- [ ] also update React wrapper
- [ ] update Storybook docs
- [ ] use [visual design checklist](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/wiki/Definition-of-done-(Visual-QA-checklist)) before opening a PR (with emphasis on numbers 1, 2, and 6)
- [ ] update [migration guide](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/feat/carbon-for-ibm-dotcom-v2/docs/dotcom-v2-migration.md) if necessary ([here](https://github.com/carbon-design-system/ibm-products/blob/main/docs/guides/v2.md) is a good example of how the guide could look)
- [ ] update unit tests where necessary (tracked in https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10369)
  - Note: Currently there is no standardization of tests, duplicate and/or redundant tests, and inconsistency in UI testing. The team consensus is to modify the tests as necessary (markup/name changes, etc) but to give this lower priority if it becomes a blocker in completing a particular component. The tests will get an overhaul in the future, so it is unnecessary to get them completely updated.

```[tasklist]
### Components
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10721
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10723
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10724
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10725
- [ ] #10050
- [ ] #9615
- [ ] #9621
- [ ] #10453
- [ ] #10384
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10751
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10807
- [ ] #10329
- [ ] #10199
- [ ] #10244
- [ ] #10306
- [ ] #10073
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10726
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10752
- [ ] #9590
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10753
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10754
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10747
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10808
- [ ] #10454
- [ ] #10432
- [ ] #10359
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10809
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10850
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10852
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10970
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10851
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10848
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10750
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10722
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10786
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10787
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10788
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10856
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10855
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10789
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10859
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/11045
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10937
- [ ] [Component] Logo grid (TBD)
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10858
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10847
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10854
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10790
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10806
- [ ] #10514
- [ ] #10512
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10756
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/11026
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/11025
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10755
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10853
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/11046
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10905
```

```[tasklist]
### Deprecated Components
- [ ] example
- [x] [Component] Content group cards (deprecated)
- [x] [Component] Content block media (deprecated)
- [x] [Component] CTA section (deprecated)
- [x] [Component] CTA block (deprecated)
- [x] [Component] Content block mixed (deprecated)
- [x] [Component] Content block cards (deprecated)
- [x] [Component] Content group simple (deprecated)
- [x] [Component] Card section simple (deprecated)
- [x] [Component] Content group pictograms (deprecated)
- [x] [Component] Content block segmented (deprecated)
- [x] [Component] Card section carousel (deprecated)
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10746
- [x] [Component] Link list section (deprecated)
- [x] [Component] Tabs extended with media (deprecated)
- [x] [Component] Content block horizontal (deprecated)
```
