### ISSUE TITLE
[Component] Tabs extended

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#10756]
Component [review notes](https://ibm.ent.box.com/notes/1204686003278)

[Tabs extended v2 design specs](https://www.figma.com/file/zFcPEDXLThKHH5dIrUth5S/Tabs-extended-v2?type=design&node-id=10%3A6400&mode=design&t=v23ZMK4zkKKMnmbL-1)

```[tasklist]
### Tasks
- [x] Update tabs extended to use carbon wc tabs – but 16px type size
- [x] Use v11 type styles
- [x] Use v11 color styles
- [x] Deprecate `vertical` variant
- [x] Storybook demo option with pre populated content item horizontal (?)
```
