### ISSUE TITLE
[Design] Component enhancements tracking

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#10757]
```[tasklist]
### Tasks
- [ ] In page banner color options
- [ ] Lead space 50/50
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/9830
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/9621
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10129
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10155
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10154
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10792
```
