### ISSUE TITLE
[carbon-web-components]: finalize Storybook v7 update

### ISSUE THREAD

**Issue by IgnacioBecerra** [carbon-design-system/carbon-for-ibm-dotcom#11496]
All the stories have now been merged, but there have been some issues we need to fix before finalizing the update.

```[tasklist]
### Tasks
- [x] resolve circular dependencies in `.mdx` and `*.stories.ts` files sometimes prevent stories to load at first
- [x] remove the `<Meta>` from some `.mdx` files as it prevents loading when different stories share the same documentation file
- [x] removing unattached `.mdx` files from showing up on the sidebar as standalone docs
- [x] Replace `Description` with `Markdown` in all the doc files, as well as updating some other deprecated SB functions
- [x] Update the only missing story: `Stack`
- [x] Prepare for incoming merge with main
```
