### ISSUE TITLE
Audit example pages

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#11528]
## Audit the example pages
We need to audit the examples pages from v1 and identify which components have been deprecated and what needs to be updated per page to help the developers know what to fix in the [update sample pages](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-web-components-test/issues/139) issue.

### Task
- Review each page
- Look for deprecated Content blocks
   - We will want to swap all copy from "Content block segmented" to "Content block" 
   - Look for other deprecated components and identify what we need to swap with
- We should estimate if we can list out instructions for the devs or if we want to provide a new design file
   - If we want to provide a new design file we should estimate the effort
   - We can also determine that we don't need so many pages!

### Pages
- [ ] [Example page A](https://carbon-design-system.github.io/carbon-for-ibm-dotcom-web-components-test/canary/example-page-a/index.html)
- [ ] [Example page B](https://carbon-design-system.github.io/carbon-for-ibm-dotcom-web-components-test/canary/example-page-b/index.html)
- [ ] [Example page C](https://carbon-design-system.github.io/carbon-for-ibm-dotcom-web-components-test/canary/example-page-c/index.html)
- [ ] [White theme Example page](https://carbon-design-system.github.io/carbon-for-ibm-dotcom-web-components-test/canary/white-theme-page/index.html) 
- [ ] [Dark theme Example page](https://carbon-design-system.github.io/carbon-for-ibm-dotcom-web-components-test/canary/g100-theme-page/index.html) 

### Documenting
- Documenting the pages in a [BoxNotes](https://ibm.ent.box.com/notes/1442438265220)

----

```[tasklist]
### Dev issues for each Page:
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom-web-components-test/issues/140
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom-web-components-test/issues/141
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom-web-components-test/issues/142
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom-web-components-test/issues/143
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom-web-components-test/issues/144
```
