### ISSUE TITLE
[web-components]: upgrade Storybook to v8

### ISSUE THREAD

**Issue by kennylam** [carbon-design-system/carbon-for-ibm-dotcom#11537]
Upgrade `@carbon/ibmdotcom-web-components` to Storybook 8.

The following knobs/controls should all be removed except where noted.
- card label
- copy, cta copy, quote copy
- all href/url (except `leaving ibm`)
- description, long description
- eyebrow
- image alt text
- heading (except `leadspace-block`/`leadspace-search` for highlight)
- subheading

> [!Note]
> * Convert tasklist items to issues as they get assigned.
> * Work off the `feat/dotcom-wc-sb7-vite` branch

```[tasklist]
### Package
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/11542
```
```[tasklist]
### Components
- [ ] back to top
- [ ] background media
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/11615
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/11538
- [ ] callout quote
- [ ] callout with media
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/11614
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/11616
- [ ] card section carousel
- [ ] card section offset
- [ ] card section simple
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/11612
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/11613
- [ ] content item row
- [ ] content item
- [ ] content section
- [ ] cta block
- [ ] cta section
- [ ] cta
- [ ] dotcom shell
- [ ] expressive modal
- [ ] feature card
- [ ] feature section
- [ ] filter panel
- [ ] footer
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/11679
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/11678
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/11681
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/11688
- [ ] lead space block
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/11700
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/11699
- [ ] leaving ibm
- [ ] lightbox media viewer
- [ ] link list section
- [ ] link list
- [ ] link with icon
- [ ] locale modal
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/11701
- [ ] masthead
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/11687
- [ ] scroll animations
- [ ] search with typeahead
- [ ] structured list
- [ ] table of contents
- [ ] tabs extended
- [ ] video player
- [ ] content block
```

```[tasklist]
### Components (deprecated)
- [ ] content block cards
- [ ] content block horizontal
- [ ] content block mixed
- [ ] content block segmented
- [ ] content block simple
- [ ] content group cards
- [ ] content group pictograms
- [ ] content group simple
- [ ] content group
- [ ] content block card static
- [ ] content block headlines
```

```[tasklist]
### Experimental
- [ ] masthead with scoped search
- [ ] pricing table
```

```[tasklist]
### IBM components
- [ ] notice choice
```
