### ISSUE TITLE
[carbon web components]: update build process

### ISSUE THREAD

**Issue by kennylam** [carbon-design-system/carbon-for-ibm-dotcom#11877]
Update build process for `@carbon/web-components` to more closely align with `@carbon/react`.

```[tasklist]
### Tasks
- [x] remove `gulp` builds - prefer `rollup` instead (https://github.com/carbon-design-system/carbon/issues/17167)
- [x] cleanup unnecessary project files (yarn.lock, .yarnrc.yml, percy.json, etc)
- [x] remove unnecessary package deps and/or ensure shared deps (with Core) are the same version
```
