### ISSUE TITLE
[carbon web components]: migrate to Carbon monorepo

### ISSUE THREAD

**Issue by kennylam** [carbon-design-system/carbon-for-ibm-dotcom#11875]
This issue tracks all the tasks necessary to migrate the `@carbon/web-components` package to the Carbon monorepo.

```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/carbon/issues/17167
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/11877
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/12021
- [ ] https://github.com/carbon-design-system/carbon/issues/17576
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/12020
- [x] [Communications]: Announce migrations in support slack channels
- [ ] https://github.com/carbon-design-system/carbon/issues/17572
- [ ] https://github.com/carbon-design-system/carbon/issues/17575
```

**Comment by tay1orjones** [comment]
Another piece of this we should discuss is issue mgmt after the migration - we'll need to consolidate or parse out the overall triage process, labels, github projects, etc.

**Comment by kennylam** [comment]
https://github.com/carbon-design-system/carbon/issues/17572 and https://github.com/carbon-design-system/carbon/issues/17575 moved to Carbon monorepo as separate issues. 

> Another piece of this we should discuss is issue mgmt after the migration - we'll need to consolidate or parse out the overall triage process, labels, github projects, etc.

https://github.com/carbon-design-system/carbon/issues/17574 created to address these topics.
