### ISSUE TITLE
Learn page layout pattern spec updates

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/carbon-for-ibm-dotcom#1507]
### User story
As a maker of IBM.com experiences, I need design specs for the layout patterns that accurately reflect what's available in code so that I can design, build, and communicate with a clear understanding of what to expect.

### Notes
There are a few different cases where the design spec may not reflect eh code accurately:
- Some of the designs were changed during development for various reasons
- Some of the designs specs were not created accurately as we went through the ontological restructuring of the patterns and subpatterns.

### Acceptance criteria
All of the following patterns have dedicated, separate, and accurate design specs in their respective Box folders.
- [ ] Card section
- [ ] Card section — simple
- [ ] Card section — with images
- [ ] Lead space
- [ ] Content block — mixed groups
- [ ] Content block — segmented
- [ ] Content block — simple
- [ ] Content block — with media
- [ ] Content group — simple
- [ ] Content group — with cards
- [ ] Content group — with pictograms
- [ ] Feature card
- [ ] Button group
- [ ] Card
- [ ] Content block
- [ ] Content group
- [ ] Content Item
- [ ] Content Section
- [ ] Link list
- [ ] Pictogram item
- [ ] Table of Contents

**Comment by RobertaJHahn** [comment]
Linked issues closed.  Closing
