### ISSUE TITLE
Hills workshop

### ISSUE THREAD

**Issue by larahanlon2** [carbon-design-system/carbon-for-ibm-dotcom#1618]
DDS team is planning to write Hills. In order to successfully create Hills together, we need research and alignment around core findings and artifacts. 

### Additional information
- Linda and Roberta are tentatively planning workshop for March 25–26
- Resources and notes on Hills available on [Box](https://ibm.ent.box.com/folder/68825753991)

### Tasks
- [ ] Lara to collect personas and share with DDS leadership to determine if they need updates
- [ ] Lara to set up a stakeholder map and share with Linda to complete
- [ ] Lara to create draft of as-is scenario(s)
- [ ] Lara to find a facilitator and confirm availability
- [ ] DDS leadership to draft mission statement and share with team
- [ ] Linda to collect metrics including NPS, # of pages, # of visitors, page load (CSS), # of adopters (DGC)

### Acceptance criteria
- All research and pre-work to be shared with DDS team in advance of workshop
- All DDS team members to complete EDT practitioner badge training by March 23

**Comment by larahanlon2** [comment]
This is back on track! Updates:

- Target dates for workshop are June 3rd and 4th.
- Facilitators include Emery Ford with support from Abigail Sirus.
- Lara working with Emery on prep work and draft agenda.
- Lara to confirm with Nigel if there is any available funding to cover Emery's time.

**Comment by RobertaJHahn** [comment]
Done.  Closing
