### ISSUE TITLE
Create and publish the "CTA Guideline" on the wedding cake website

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-dotcom#197]
_chsanche created the following on Jan 21:_  

 ## User story

As a designer and copywriter, I need a rule for me to effectively create the CTA label so that I can not only let the user know what I want them to do next but also create a cohesive tone and voice across the website.

## Deliverables
- General guideline for CTA label creation

### Notes
- This task link to the Voice and Tone guideline. It's my understanding we do not currently have.
- We need to work with the content team for this.

### Tasks
- [ ]  Set up a time to talk with the Content team.
Conduct quick research on what we currently have in IBM, Marketing Team and Carbon.
- [ ] Decided who is going to lead the task (I think the content team will be the one who provides us the guideline content)
- [ ] Once we have the finalized guideline, we will host the content on the website
- [ ] If we need a new page for it, the page will be based on the website page template
- [ ] Share the guideline with the team 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/473_

**Comment by jeffchew** [comment]
_On Mar 20, chsanche commented:_
**Note:** Microscopy presented by Martin has good insight.
https://ibm.box.com/s/ifw8yd65o71n9yskw7kbktfmndxd75s3

**Comment by jeffchew** [comment]
_On May 14, chsanche commented:_
@Olivia-Flory @larahanlon FYI on this Epic.

**Comment by JennySanchez** [comment]
The Call to Action guideline is created and live on the [website](https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/patterns/call-to-action). The EPIC will be closed.

FYI @RobertaJHahn
