### ISSUE TITLE
Homepage design for on the wedding cake website

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-dotcom#201]
_chsanche created the following on Feb 10:_  

 ### As a design system adopter, I need a way to find the information* or knowledge** I need so that I can start creating, coding, or planning.

*information": how to get started.  **Knowledge: typographical basics

## Deliverables
- Homepage design

### Notes
- We will need to work on a new homepage based on the IA work outcome with the Carbon Team since we will have ONE homepage for both sides of the design system.

### Possible steps
- [ ] Design home page based on the outcome of https://github.com/carbon-design-system/ibm-dotcom-library/issues/201 
- [ ] Get feedback from Mike and the bigger design community
- [ ] Work on design iterations
- [ ] Finalize the design

### Acceptance criteria
- Have the homepage design approved by Linda and Wonil
 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/556_

**Comment by jeffchew** [comment]
_On Feb 10, chsanche commented:_
@Wonil-Suh1 This is the EPIC for the homepage design as discussed.

**Comment by jeffchew** [comment]
_On Jun 24, chsanche commented:_
**FYI:** The user story, acceptance criteria and etc will be updated.

**Comment by jeffchew** [comment]
_On Jun 28, chsanche commented:_
**Update:** The user story, acceptance criteria and etc are updated.

**Comment by RobertaJHahn** [comment]
Wedding cake site will follow the cupcake site.  The cupcake MVP is scheduled to finish Dec 20, 2019.

**Comment by RobertaJHahn** [comment]
Strategy has changed with the Carbon discussions.  Closing
