### ISSUE TITLE
Create User Personae and User Journeys

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-dotcom#229]
_Benjamin-Hansen1 created the following on May 24:_  

 ## User story

As a DDS or Carbon team member, I need to understand our users, their behaviors, needs, processes, drivers, etc.- so that I can make sure the DDS/Carbon experience provides ultimate value to them.

## Deliverables

- [ ] Documented user personae for key archetypes of DDS and Carbon 
     - [ ] Designer
     - [ ] Developer
     - [ ] Stakeholder (page/product owner, manager ...)
     - [ ] Executive
- [ ] User Journys for key archetypes of DDS and Carbon (part of/conected to each persona)
     - [ ] Designer
     - [ ] Developer
     - [ ] Stakeholder (page/product owner, manager ...)
     - [ ] Executive
- [ ] A guideline on how to use personae and Journey maps
- [ ] Expanded list of additional needed personae and new Epic created

## Acceptance Criteria

- [ ] All deliverables completed
- [ ] Publish to the Knowledge Base for use across IBM
 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/884_

**Comment by RobertaJHahn** [comment]
All linked issues closed.  Closing.
