### ISSUE TITLE
Error page: UI/Vis design study

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-dotcom#349]
_Wonil-Suh1 created the following on Aug 13:_  

 ### User story
As a user, I need to be informed of the error that occurred and the next steps.

### Acceptance criteria
- [ ] multiple design directions have been produced
- [ ] minimum two candidates have been presented to DGC design review
- [ ] identified the final direction
 
### Current design
![screencapture-ibm-lksdjf-2019-10-07-20_43_21](https://user-images.githubusercontent.com/30183447/66359222-3c495e80-e944-11e9-917d-35ebd252e778.png)

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1448_

**Comment by wonilsuhibm** [comment]
Latest design explorations with modified `display-03` type.

![error-page--design--1 0 0--35](https://user-images.githubusercontent.com/30183447/67150020-46daf080-f280-11e9-9574-50aed3319220.png)


![error-page--design--1 0 0--35--modal](https://user-images.githubusercontent.com/30183447/67150016-332f8a00-f280-11e9-8ac0-75f1660cba26.png)

**Comment by wonilsuhibm** [comment]
![Screen Shot 2019-11-14 at 10 09 43 PM](https://user-images.githubusercontent.com/30183447/68914108-84218980-072b-11ea-820d-aab8abe7643e.png)
An example - we could show the 2x grid behind the message like this.

**Comment by wonilsuhibm** [comment]
One concept idea:
404 error happened because:
- We made a mistake. Help us fix it.
- You are looking for something greater. Let's work together to make it happen!

**Comment by oliviaflory** [comment]
Duplicate
