### ISSUE TITLE
Error page: final design

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-dotcom#350]
_Wonil-Suh1 created the following on Aug 13:_  

 ### User story
As a user, I need to be informed of the error that occurred and the next steps.

### Notes
Details on the current error pages is captured in the epic, https://github.com/carbon-design-system/ibm-dotcom-library/issues/350.

### Acceptance criteria
- [ ] final design has been produced
- [ ] final design has been reviewed by IDL
- [ ] final design has been approved by DGC design leadership
 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1449_

**Comment by oliviaflory** [comment]
Duplicate
