### ISSUE TITLE
Web component: Locale Modal - Add Link with icon

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#3648]
This epic contains functional and design links that define the scope of the deliverable.  This epic also includes links to all of the work required to deliver the component. 

This was a feature request from Lara.  

#### Additional Information

-  Corresponding React epic (#3651)
- [Functional spec Box link](https://ibm.ent.box.com/folder/82255256134)
- Story within Storybook with corresponding knobs
- Utilize Carbon
- Create with Shadow DOM and Custom Elements standards
- **See the Epic for the Design and Functional specs information**
- Design QA testing issue (#3649)
- Prod QA testing issue (#3650)

#### Acceptance criteria
- [ ] Include README for the web component and corresponding styles
- [ ] Create Web Components styles in styles package
- [ ] Do not create knobs in Storybook that include JSON objects
- [ ] Break out Storybook stories into multiple variation stories, if applicable
- [ ] Create codesandbox example under `/packages/web-components/examples/codesandbox` and include in README
- [ ] Minimum 80% unit test coverage
- [ ] If a design is provided, the Designer is included as a Reviewer in the Pull Request
- [ ] Provide a direct link to the deploy preview for the designer in the Pull Request description
- [ ] A comment is posted in the Design QA issue, tagging Designer, when development is finished
- [ ] The Storybook link is added to the Design QA issue for their testing
- [ ] A comment is posted in the Prod QA issue, tagging Praveen and Chetan, when development is finished

**Comment by RobertaJHahn** [comment]
@IgnacioBecerra The PR should be linked to the development issues, not the epic.  The epics remain in the Prioritized Epics pipeline until the link issues are closed.  The dev issue is (#3446).  Gui referenced your PR in that issue.  I am moving this epic back to the Prioritized Epics pipeline and assigning Ignacio to the dev issue as he did the work.
