### ISSUE TITLE
Address issues that should be resolved before v1.0.0 release of Web Components

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/carbon-for-ibm-dotcom#4100]
### The problem

We have several breaking changes in Web Components on the horizon and should address them before Web Components' `1.0` release. The current list is at the Additional information section below.

### The solution

Address them and identify more breaking changes as we find them.

### Additional information

- [x] ~~Move Redux code to a separate package (#3258) - PR: #4252~~
- [x] ~~Determine the minimum TypeScript version (#4101) (Note: For TypeScript users only, non-TS users are not affected by this)~~
- [x] ~~Consider changing cta slots to footer (#4112)~~
- [x] ~~link-with-icon: See if there is a use case to place icons at the left and at the right at the same time (#4114) - PR: #4117~~
- [x] ~~Button group: Consolidate button kind enum to one of Carbon core (#4115)~~
- [x] ~~Quote: Consider removing inverse attribute (#4122)~~
- [x] ~~Modal: Consolidate the size attribute to core modal one (#4123)~~
- [x] ~~Icon: Consolidate to link-with-icon (#4124)~~
- [x] ~~feature-card-block-medium: Consider consolidating its card portion (#4125)~~
- [x] ~~Move internal link component to carbon-web-components (#4143)~~
- [x] ~~card-group: See the purpose of cardGroupItemSelector static property (#4144)~~
- [x] ~~CTA: Consider splitting its mix-in (#4159)~~
- [x] ~~Quote: Consider making enums dash-cased (#4160)~~
- [x] ~~Callout: Consider removing base callout or making it as a mix-in (#4170)~~
- [ ] Components: Investigate the requirement of grid usage (#4174)
- [x] ~~Card: See if inverse attribute/property is still needed (#4175)~~
- [x] ~~Web Components: Align the naming pattern of static properties for CSS selectors (#4193)~~
- [x] ~~Quote: Consider making slot names dash-cased (#4230)~~
- [x] ~~Leadspace: Consider removing theme attribute (#4250)~~
- [x] ~~Components: Ensure forward-compatible with React wrappers in Node 14 (#4251)~~
- [x] ~~CTA: Move the mixin code to component-mixins (#4280)~~
- [x] ~~feature-card-block-large: Render heading portion outside the card (#4283)~~
- [x] ~~Components: Introduce a component for heading/copy, etc. (#4326)~~
- [x] ~~Markdown: Consider rendering to light DOM (#4327)~~
- [x] ~~Button group: Guide how to make all items have equal width/height (#4375)~~
- [x] ~~Callout: Clean-up the base mix-in (#4559)~~
- [x] ~~Content pattern: Determine what the default slot be used for (#4627)~~
- [x] ~~Content block: Automatically define slot attribute for the copy component (#4851)~~
- [x] ~~Link list: Remove `bx--link-list__split` CSS class (#4863)~~
