### ISSUE TITLE
Summit presentation and activity Mural setups

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom#4219]
This task contains two subtasks:

#### Tasks

**Mural board setups for Day one activity**

As a Carbon for IBM.com team member, I need a way to take the summit participants through exercises that will help them discover questions they might have for the migration so that our team spot opportunities to support adopters better in the future.

**Mural board setup for general summit feedback**

As a participant of the summit, I would like to share my feedback with the Carbon for the IBM.com team so that they can make improvements to a future event like this or follow up with me for the questions I might have.

**Summit presentation slides for the Carbon for IBM.com website and IBM.com Web Standard website**

As a Carbon for IBM.com team member, I need a way to take the summit participants through the websites our team owns so that the participants know where to find the relevant information and tools for their adoption.

#### Acceptance criteria
- [x] Mural board setups for Day one activity is ready for use
- [x] Mural board setup for general summit feedback is ready for use
- [x] Summit presentation slides is reviewed with Wonil and good to go

**Comment by JennySanchez** [comment]
- Mural board setups for Day one activity can be viewed [here](https://app.mural.co/invitation/mural/digitaldesignsystemsquadwork2176/1602539020490?sender=chsanche&key=252fa8de-738a-4917-8ff4-0feb999a5361).
- Mural board setup for general summit feedback can be viewed [here.](https://app.mural.co/invitation/mural/digitaldesignsystemsquadwork2176/1602613456415?sender=chsanche&key=6205e7db-1df1-4d73-8ad6-3774fb530c60)
- Summit presentation slides can be found [here.](http://ibm.biz/Summit_Presentation_Recording_Resources?_ga=2.88676440.2139681086.1603299952-613257676.1596556200)
