### ISSUE TITLE
Design the Checklist for IBM.com Web Standard website

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom#4517]
> As an IBM.com Web Standard adopter,

> I need a way to view all the requirements and learn all the standards I need to meet

> So that I can create an user centered experience for IBM.com visitors.

#### Note
Design ideation and conversation detial can be viewed via #150 on the ideation board.
https://github.com/carbon-design-system/digital-design-ideation/issues/150

#### Tasks
- [ ] Work on the designs based on the ideation outcome
- [ ] Share design with team members and get feedback
- [ ] Revised design based on the feedback
- [ ] Finalize the design

**Comment by JennySanchez** [comment]
Issue moved to [carbon-design-system/carbon-for-ibm-dotcom-website #748](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/issues/748) via [**ZenHub**](https://www.zenhub.com/)
