### ISSUE TITLE
[Lead space] medium variation

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/carbon-for-ibm-dotcom#4753]
## Task

A lot of efforts has been done to identify the height and usage for different lead spaces, so far only [the tallest ](https://ibmdotcom-web-components.mybluemix.net/?path=/story/components-leadspace--default-with-no-image)was built. **Our goal this round would be to design and spec 1-2 more variants that might be shorter, more practical, and allow more content to show above the fold.**

- [x] Design explorations & synthesis of past work #5197 
- [x] Review with core team + design leads of AEM & HC 
- [x] Spec 
- [ ] Update documentation (website) FYI @JennySanchez 
- [ ] Build 

### Additional Information
- [box folder with updated specs](https://ibm.box.com/s/d9jey3rlfxqmxu059f0x9dtcx7f5ehuh)
- [Original size standards](https://ibm.box.com/s/iy3rscrww6sz2ioz7qbxhee040m5727e)
- [Solutions page template](https://ibm.box.com/s/mtwz67xkesfe6wf038tw8z7h6atrus2f)
- [Services page template](https://ibm.box.com/s/4p0p344zjmu1e273u60g5ytjdasd1rs9)
- [Support landing page](https://share.goabstract.com/5ca0af92-0b72-4bf0-8486-91a109e23d33)
- [Products landing page](https://share.goabstract.com/ffb87f12-92f3-432f-87ba-107de1aeb796)

### Resources

- Current one in our library: https://ibmdotcom-web-components.mybluemix.net/?path=/story/components-leadspace--default-with-no-image

- Different use cases are captured in Ideation repo issue: https://app.zenhub.com/workspaces/carbon-for-ibmcom-5d449f3642eb1962336cbe52/issues/carbon-design-system/digital-design-ideation/126

- Research and explorations from Lara: 
> Here is the lead space research work I shared today during Reboot design review. Feel free to dig around and challenge anything in the Sketch file or report. I added questions and potential directions to move forward with but all of this will need further review and probing by design and content strategy! Let me know if you have questions.
Sketch file with competitor audits and internal audit/journey proposals:
https://ibm.box.com/s/jyhzoysxeca8lenhz37gf8hfreoturjm
Research report:
https://ibm.box.com/s/2fywsn7qwhev2ay4ia3jknhh17ugx5vj
Draft content for lead spaces pattern (to publish on IBM.com Library)
Boxnote:
https://ibm.box.com/s/00ayfghsn26ge4g19lcn59buylav2xix

- Hybrid Cloud library: https://pages.github.ibm.com/MSC-Cloud/hc_fractal/components/detail/2a--white.html

- AEM proposal: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/5094

**Comment by RobertaJHahn** [comment]
Some examples of Events and Think Lead space modifications.  https://www.ibm.com/events/  and https://www.ibm.com/events/think/

Rafeal to provide more details about the sizes to Jenny and document here.

**Comment by shixiedesign** [comment]
Consider AEM's recommendation: 
https://app.zenhub.com/workspaces/carbon-for-ibmcom-5d449f3642eb1962336cbe52/issues/carbon-design-system/carbon-for-ibm-dotcom/5094

**Comment by shixiedesign** [comment]
**Documented slack discussion:** 

### Lead space variants

- super
- tall (default)
- medium
- short


### Alignment options
left
center


### Type options (this one requires more discussion)

semibold
light
