### ISSUE TITLE
Adopter collaboration: Content model mapping project with Michael F (Reboot Team)

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom#4894]
> As a Carbon for IBM.com adopter and IBM.com makers, 

> I need a way to find the layout I need based on the style model and also tied to the component

> So that I can get started with the right layout without confusion.

#### Project note:

- Michael on the Reboot Team purposed a UI design (design file will be attached as soon as received) with the search and filtering functionalities to support IBM.com makers to find the available content models based on the style model efficiently. 

- We had a call and discussed a few ideas for execution. In the end, both teams agreed to test out the idea of adding the content models info to the components website pages on the Carbon for IBM.com website first, as an MVP approach.

- Amount all the components website pages, we will work on the ~"Content block – with media” first and~ "Leads pace – block" ~second~.

- Michael is new to the Carbon for IBM.com website and new to the editing with the Markdown process.

#### Steps

- [x] Michael finalized the content models info for the ~Content block – with media~ "Lead space – block".
- [x] Michael work on the content edits via Markdown and will reach out to Jenny with assistance as needed.
- [x] Asset image creation is done (Michael might collaborate with Visual Designers on Reboot or Jenny as needed)
- [x] Publishing with markdowns is done.
- [x] QA'd by Jenny.
- [x] Web page preview is approved by Lily, Linda, and Wonil.
- [x] PR merged by Jenny.

#### Acceptance criteria
- [x] Lead space – bllock ~Content block – with media~ content model section is added and live on the website.

**Comment by JennySanchez** [comment]
**FYI:** @ljcarot @RobertaJHahn @wonilsuhibm

**Comment by JennySanchez** [comment]
### Task notes:

**Content model slides Michael shared in the Content Model Discussion call (Tue 01/12/2021 9:00 AM - 10:00 AM CT) attached below.**

[https://app.zenhub.com/files/193129061/20bc297b-1379-4b1b-bb6a-c721061bed66/download](https://app.zenhub.com/files/193129061/20bc297b-1379-4b1b-bb6a-c721061bed66/download)

![Screen Shot 2021-01-19 at 11.29.21 AM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/c7d3a470-24f3-4731-b37e-f68a11028fce)

**Below is the sprint focus list from Micharl:**
![Screen Shot 2021-01-19 at 10.09.39 AM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/9a52a698-fc46-4960-a14f-341670605496)

**Comment by JennySanchez** [comment]
Met with Michael and Jina today to go over the markdown edit process. Michal mentioned he is going to use "tabs" for the use case content and will share more with us when he is ready.

**Comment by JennySanchez** [comment]
@wonilsuhibm The **Content guidance** section (see screenshot below) for the Lead space – block is ready for your review. The preview link can also be found [here](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/pull/831). 

![Screen Shot 2021-01-27 at 9.37.34 AM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/8a89f0e4-4d3b-4a65-9b90-9da558e727b6)

**Comment by JennySanchez** [comment]
PR merged.
