### ISSUE TITLE
Planning and work for the Marketing Studio design deep dive session

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom#4977]
> As a Carbon for IBM.com team member,

> I need to plan and prepare related materials for the 2021 Marketing Studio Design dive sessions,

> So those adopters from the Marketing Studio org. know how to get support for adoption and contribute back to the Carbon for IBM.com.

### Tasks

- [ ] Watch the tutorial videos on the [Carbon website](https://www.carbondesignsystem.com/designing/tutorials/)
- [ ] Ideate on the content or topic for the session ([Mural board](https://app.mural.co/invitation/mural/digitaldesignsystemsquadwork2176/1611255446531?sender=wonilsuh19286&key=05c53a48-54e9-4e18-96d9-aec710ab5648))
- [ ] work with Wonil to finalize the topic
- [ ] create content materials (if needed)
- [ ] playback to the DDS designers or the team for feedback and alignment purpose

#### Acceptance criteria

 - [ ] Items listed above are completed and ready to go

**Comment by JennySanchez** [comment]
Close this task since Wonil created #4995 for the work.
