### ISSUE TITLE
MSC Summit designer deep-diver session 3: using the system

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/carbon-for-ibm-dotcom#4995]
February 25
8–9 AM ET

**Comment by JennySanchez** [comment]
@wonilsuhibm I created task issue #4977 for the work but since you created this one, I will close #4977 - FYI.

---- 

> As a Carbon for IBM.com team member,

> I need to plan and prepare related materials for the 2021 Marketing Studio Design dive sessions,

> So those adopters from the Marketing Studio org. know how to get support for adoption and contribute back to the Carbon for IBM.com.

### Tasks

- [ ] Watch the tutorial videos on the [Carbon website](https://www.carbondesignsystem.com/designing/tutorials/)
- [ ] Ideate on the content or topic for the session ([Mural board](https://app.mural.co/invitation/mural/digitaldesignsystemsquadwork2176/1611255446531?sender=wonilsuh19286&key=05c53a48-54e9-4e18-96d9-aec710ab5648))
- [ ] work with Wonil to finalize the topic
- [ ] create content materials (if needed)
- [ ] playback to the DDS designers or the team for feedback and alignment purpose

#### Acceptance criteria

 - [ ] Items listed above are completed and ready to go

**Comment by JennySanchez** [comment]
![Screen Shot 2021-02-19 at 2.51.55 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/0db357d3-d574-40b1-b7d1-6a3b137ead56)

**Comment by JennySanchez** [comment]
Design deep dive session 3 completed.
