### ISSUE TITLE
[CTA Section variant] aka "Promo group"

### ISSUE THREAD

**Issue by sbahl1** [carbon-design-system/carbon-for-ibm-dotcom#5201]
This epic will include linked issues that define the Digital Design Squad work required.  This component is needed in the March release.

**Adopter**: AEM
**AEM used name of Component** : Promo Group
**Type of change**- New

### Final design spec
https://ibm.box.com/s/shr0pnhof0yzk2b5lh0nokwopgxxb9rr

### Change Description: 
- Add new component with 4 variants (Pictogram, media, statistic and text) 

### Link 
- Invision document is here https://ibm.invisionapp.com/share/F9O0RPZHT46#/screens/319811795
- Pull request https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/5142

#### Functional specs
[Content section](https://ibm.box.com/s/mwz8d62bxgqlu84rwt7yfpa3lgray6sc) update
[CTA block](https://ibm.box.com/s/1mbmay093kclwwjhuhmux0kqzptvpgj3) creation
[CTA section](https://ibm.box.com/s/lwc9yt046wphh568l4qhe6pjfu23acqg) update

Content section heading optional (create issue) https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/5487

### Acceptance criteria 

To promote this component to core and remove feature flag: 

- [x] Design adjustments clean up
- [x] Name it
- [x] Visual and functional specs 
- [ ] Development to implement the design adjustments (list to be confirmed)
-- swap out child pieces with "Content item"
-- type style changes
-- pictogram position change
-- add 3 col layout for content items under main block
-- create react wrapper for it
-- pull out "CTA block" as a component
-- remove "Promo group" & "Promo item"
- [ ] Visual & prod QA

### Examples from design spec

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/5bc33bc8-12da-44a1-90ec-0b121ed0b6f6)
![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/4ab8ca5f-0f74-49b9-824a-097d6a8b5c86)
![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/d958fc6d-8b7d-41e6-bb6b-357fb3929ae9)
