### ISSUE TITLE
[Lead space] Structure and variant overhaul

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#5347]
Lead space is currently showing legacy naming convention and disorganized variants. This needs to be cleaned up to match the following, where first col on the right are Storybook stories, and the rest are options. Implementation wise, we will have to: 

- Deprecate `Small` and `Small with image`
- Add height options for `super`, `tall` which would be default, `medium` and `short` 
- Knob for adding button, button group, image
- Design Box folder:  https://ibm.ent.box.com/folder/94761007991?s=d9jey3rlfxqmxu059f0x9dtcx7f5ehuh

Desired storybook for `Lead space` is: 
```
Lead space
|--- Super
|--- Tall
|--- Medium
|--- Short
|--- Centered
``` 
![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/823cbfb2-56be-4960-b383-c123b5f9c695)

To do 
- [x] Design Lead space & visual spec #5256
- [x] Lead space functional spec v2.0 FYI @photodow 
- [x] Web components
- [x] React components
- [ ] Website FYI @JennySanchez

**Comment by RobertaJHahn** [comment]
Shixie and staff will document the dev issues to be created. Tag Roberta to create React and WC dev issues. Visual QA & Prod QA, web site also
