### ISSUE TITLE
[Content group - banner] 

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#5354]
This component is fresh off the press on March 3rd. Design is reviewed. Next steps include: 
- [x] final spec sketch & PDF https://ibm.box.com/s/tqp7c0wm99ha0b7jrm0sqhq3whwdjv84
- [x] naming & func spec #5368
- [ ] hand off to development

**Notes (updated Mar 15):**
- Component: 12 col promo text block, to be delivered wrapped in "Content section"
- optional heading-01 
- min 1 CTA

### Final design spec: 
https://ibm.box.com/s/tqp7c0wm99ha0b7jrm0sqhq3whwdjv84
![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/bbccdcd4-a0fd-4323-b6b3-58a36836927d)

#### Additional Information
- [Design spec Box folder](https://ibm.box.com/s/tqp7c0wm99ha0b7jrm0sqhq3whwdjv84)

**Comment by RobertaJHahn** [comment]
@shixiedesign Is a design issue needed or will you post the designs into the Box folder and include the link in this epic?

**Comment by shixiedesign** [comment]
Oof how did I miss these github comments for 12 days - 
@RobertaJHahn the design spec boxfolder is updated in issue description, also here https://ibm.box.com/s/tqp7c0wm99ha0b7jrm0sqhq3whwdjv84

@photodow your comment above might totally apply any more but some agreed is what I'd expect: leveraging `content group` and `link list`. I think we'd also need `content section` for the heading-01. Lemme know your latest thought.

**Comment by photodow** [comment]
> @photodow your comment above might totally apply any more but some agreed is what I'd expect: leveraging content group and link list. I think we'd also need content section for the heading-01. Lemme know your latest thought.

Yeah I tend to agree here, most of the questions above I believe got addressed over slack.
