### ISSUE TITLE
[CTA] Storybook naming and examples incorrect

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom#5385]
### Problem

The CTA components inside the [React](https://ibmdotcom-react.mybluemix.net/?path=/story/components-cta--button) and [Web Components](http://ibmdotcom-web-components.mybluemix.net/?path=/story/components-cta--text) Storybooks have discrepancies around the naming and the examples between the two Storybooks (see screenshots below). 

After a [discussion](https://cognitive-app.slack.com/archives/GBG66T9NK/p1614887714098800) on the team Slack channel, the React version is wrong based on James's functional spec.

`For the labels:`
![Storybook nav labels](https://user-images.githubusercontent.com/45213839/110149019-27743300-7da3-11eb-938c-08d97e2c80b7.jpg)

### Overall storybook should follow these rules:
- Components should be in alphabetic order
- The variants inside the component should be organized based on the complexity (text, button, card, feature).
- UI components with no grid info should be left aligned: 16px from top and 16px from left of viewport

The overall clean up work included above has been broken out into a separate issue (#5529 ) and included under the Component cleanup for consistency epic.  

----

### Specific defects in CTA 

- [ ] Text - should show text with an arrow icon. (React: correct. WC: need to take the "Regular type" off the CTA type knob options and use Local as default.)
- [ ] Button - should show two buttons (React: should be left aligned in viewport. WC: need to match what React has & left aligned in viewport)
- [ ] Card - should show card link. (React: should be left aligned in viewport. WC: missing corner icon).
- [ ] Feature  - should show **[Feature card block - medium](https://ibmdotcom-web-components.mybluemix.net/?path=/story/components-feature-card-block-medium--default)**. (React: correct, but wrong name, should be left aligned in viewport. WC: Headline is missing).

`For the examples:`
![Storybook samples](https://user-images.githubusercontent.com/45213839/110166697-56e26a00-7dba-11eb-825e-5da90856b283.jpg)

### Task:

- Take a look at both versions in Storybooks.
- Work on the fix

### Acceptance criteria
 - [ ] Both Storybooks show the same labels and examples for CTA components

**Comment by JennySanchez** [comment]
**FYI:** Set the Severity to a two because it impedes users significantly and can cause confusion when adopting the CTA component from design and dev perspectives.

**Comment by shixiedesign** [comment]
To be broken down into smaller issues and fixed independently.
