### ISSUE TITLE
[Beacon for IBM.com] Web UI inline test page - design work

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-dotcom#5637]
#### User Story

> As a `[user role below]`:
IBM.com application owner

> I need to:
run a report on my application page(s) through a web tool

> so that I can:
see results right away on my level of compliance in my IBM.com application

#### Additional information

 - Should be similar to something like Pagespeed Insights: https://developers.google.com/speed/pagespeed/insights/

![image](https://user-images.githubusercontent.com/1641214/112540736-ead79e00-8d88-11eb-9414-4294cf859c80.png)

 - This can possibly live under https://www.ibm.com/standards/web

#### Acceptance criteria
- [ ] Creation of sketch files for the page design

**Comment by JennySanchez** [comment]
**Note:** Follow the Carbon [Chart types](https://www.carbondesignsystem.com/data-visualization/chart-types/) styling for the design work

**Comment by shixiedesign** [comment]
Useful Carbon's status icons:
https://github.ibm.com/brand/ui-icons/issues/92

**Comment by JennySanchez** [comment]
**Task status:** 

- Shared the WIP [Overview page content ](https://ibm.box.com/s/477ljh0a6jjxv9ego1jwvmhv4k52dses)and user flow mockup with @jeffchew @kennylam, and @ljcarot to get feedback.

- Will share the flow in the demo next Tuesday to get overall feedback.

(flow)
[https://app.zenhub.com/files/193129061/80f25508-d4f8-4e96-b5e0-3714e8dbba4f/download](https://app.zenhub.com/files/193129061/80f25508-d4f8-4e96-b5e0-3714e8dbba4f/download)![Resources page update.jpg]

(note: add the card to the Resources page)
(https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/635c94ae-ab4c-4f7a-aa1b-cd49a190fad1)

**Comment by JennySanchez** [comment]
**The latest UI flow shared in the demo can be viewed below:**

[https://app.zenhub.com/files/193129061/ded180c8-8a7f-4e57-af2a-c78ad1f11fc0/download](https://app.zenhub.com/files/193129061/ded180c8-8a7f-4e57-af2a-c78ad1f11fc0/download)

**Next steps:** 

- [ ] Finalize navigation set up
- [ ] Finalize the Overview page content
- [ ] Finalize the result page format

**Comment by JennySanchez** [comment]
**Updated overview page:**

![UPDATED - Beacon for IBM.com - overview.jpg](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/d2e5aa58-0a55-4d3e-b581-885d15d4797e)

**Comment by JennySanchez** [comment]
@kennylam Below's the MVP design for the Beacon for IBM.com UI. Please let me know if you need anything else.

The Sketch work file and assets shared below can be found in the [Beacon for IBM.com BOX folder](https://ibm.box.com/s/p0ayzwztfczy7s42j26lkrt9eassvwy3).

---

**Navigation:**

![Navigation.jpg](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/24d96fbe-9e26-45cd-8997-afa814f75636)

**Flow:**
[https://app.zenhub.com/files/193129061/e90a8062-5ed3-449e-beb5-e7b6477fc000/download](https://app.zenhub.com/files/193129061/e90a8062-5ed3-449e-beb5-e7b6477fc000/download)
