### ISSUE TITLE
[Footer] Implement adjunct legal links website content publishing

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5673]
### Objective
Provide Carbon for IBM.com adopters the most up-to-date best practices and guidance they need to adopt Carbon for IBM.com.

### Task types

- [ ] Fix something on the website
- [ ] Update content on the website
- [ ] Add new Content on the website to an existing website page
- [ ] Craft and publish new content on a new website page

### Get started

- [ ] For existing website page update - navigate to the existing page on the live website, click on the `Edit this page on GitHub` text link located in the bottom left corner of the website page to get started.
- [ ] For new website content crafting - navigate to the `How to publish component usage documentation section` on the [Contribution /Components section](https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/contributing/components#how-to-publish-component-usage-documentation) and use the markdown template to get started.
- [ ] For new website page design and image creation - download the Sketch work file [here](https://ibm.box.com/s/66v0t127kdgo3xqt3u5f7dl56skpealk) to get started.
- [ ] For new or existing thumbnail image update on the Components overview page - use the master Sketch work file [here](https://ibm.box.com/s/hyzeqfb7zqov1j3es4p6kplr6r15flat) to get started.

### Acceptance criteria (The meaning of "Done")
- [ ] Updates or new Content is showing up on the live website.

---

### Additional resources

➜ For general contribution - Please visit the [Contributing page](https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/contributing/overview) for information and process detail.
➜ For the website content publishing process - Please visit the [Publishing process wiki page](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/2020-website-content-publishing-process) for detail.
➜ For how to create and submit PR - Please visit the [Submitting a Pull Request section](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/docs/developing.md#submitting-a-pull-request) to learn more.
➜ For Markdown best practices - Please visit the [Production guideline](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Carbon-for-IBM.com-Production-guidelines) to learn more.

### FAQ

**How do I name the work file for website tasks?**
Work files are named using the format: Name of the category + components/pattern/guideline + version. 

Examples:
Components-Feature card block v1.0
Guidelines-Expressive theme v1.0
Help-Overview v1.0, etc.

**How do I name an image file for a website page?**
Images are named using the format: page name - section name - usage.file format

Examples:
masthead-beheavor-default.png
footer-variations-usecase 01.jpg

See detail around image requirements [here](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Carbon-for-IBM.com-Production-guidelines#naming-conventions).

**Where do I save the work file for website tasks?**
Please save all content publishing work files (box, markdowns link, or Sketch file) in the proper sub-folder under the[ ✍️ Content + Design folder](https://ibm.box.com/s/tty3jhshkt6l18jkn2v5ac2uznyjexns).

**What are the general steps for the content task to go live on the website?**

In general, for a new component website page, the tasks involve the following steps/items.

1. Content crafting (include images, if any) are reviewed by the DDS designers
2. Content crafting (include images, if any) are finalized
3. Content is published with markdowns, and PR is ready for review
4. PR reviewed and QAed by Jenny
5. Update the [Overview page component table list](https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/components/overview/) with the guideline name, link, description, and status when the Markdown is done.
6. QA'd by Jenny.
7. Web page preview is approved by Linda, Jeff, and Wonil.
8. PR merged by Jenny.
9. Content goes live on the website.

### Questions and Support
Please reach out to @JennySanchez for a quick task or process walk-through or ask questions you may have related to this task.
