### ISSUE TITLE
[IBM.com Web Standard] Hero image update

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom#5934]
@JennySanchez commented on [Wed Oct 14 2020](https://github.com/carbon-design-system/digital-design-ideation/issues/165)

#### Objective
We need to add a hero image to the IBM.com web standard website to create a better impression when IBM.com content creators landed on the homepage.

#### Task

- [ ] Do design research and study how other IBM websites present similar content (style of the hero images or hero section treatments).
- [ ] Explore ideas and create purposed designs.
- [ ] Review the designs with Linda and Wonil.
- [ ] Finalize the design and create task issues on the Agile board for execution.

---

@JennySanchez commented on [Wed Oct 14 2020](https://github.com/carbon-design-system/digital-design-ideation/issues/165#issuecomment-708504276)

**Note:**

![Screen Shot 2020-09-29 at 8 00 34 AM](https://user-images.githubusercontent.com/45213839/96015787-95788780-0e0d-11eb-81f1-b0fbfb7d0ed3.png)

---

@RobertaJHahn commented on [Thu Apr 29 2021](https://github.com/carbon-design-system/digital-design-ideation/issues/165#issuecomment-829481033)

If this is not worked on by the end of June 2021 then can close.

**Comment by JennySanchez** [comment]
@RobertaJHahn I think we can close this issue before the end of June 2021. Let's close it.
