### ISSUE TITLE
[Expressive theme design kit] Slack comm for kit and type token changes

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#5945]
- [x] Add a deprecation notice, tracked #6014

Need to create a comms plan to cover the changes with the kit and also the type tokens. 
Communicated via Slack channels: main support channels for Dotcom, core Carbon, IDL, Sketch kit channel
Work with Carbon team to create a strategy for the communications so that both teams are equipped to answer any questions on Slack. 

Topics to be covered:
- [ ] recap of the expressive theme sunset and implications (referencing the three base components in Carbon) 
- [ ] list of type token changes, and explanation of rollout strategy (in v10 as well as v11 🤞 ) 
- [ ] changes in the Sketch kit
  - tell people where to get Sketch kit
  - show the structure of the type tokens in the flyouts

Review existing guidance to make sure it fully supports the changes:
- [x] [Designing page update](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/issues/1084)
- [x] [Expressive theme page update] (https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/issues/962)
- [ ] Any tutorial updates? Design Summit tutorials, Carbon Patterns presentation

**Comment by oliviaflory** [comment]
**_Proposed message to send to our users:_** 

Hi everyone,

The Carbon for IBM.com team has some important updates regarding the Expressive theme and the Carbon Expressive design kit. Please see below:

The Expressive Theme has been integrated into Carbon Design System’s core library. This means that expressive continues to be available to IBM.com, but now all Carbon adopters can get both productive and expressive experiences from the same library source. In the next few sprints, we will be shifting to use expressive styling and elements from core, then the Expressive Theme within Carbon for IBM.com will no longer be maintained.

In the next few months the Carbon for IBM.com team will be working to make the transition as seamless as possible for our adopters. Please visit our website to [learn more about this change.](https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/help/expressive-update/)

**Comment by janchild** [comment]
Need to create a comms plan to cover the changes with the kit and also the type tokens. 

Slack channels: main support channels for Dotcom, core Carbon, IDL, Sketch kit channel

Work with Carbon team to create a strategy for the communications so that both teams are equipped to answer any questions on Slack. 

Comms to cover the following topics:
- recap of the expressive theme sunset and implications (referencing the three base components in Carbon) 
- list of type token changes, and explanation of rollout strategy (in v10 as well as v11 🤞 ) 
- changes in the Sketch kit
  - tell people where to get Sketch kit
  - show the structure of the type tokens in the flyouts

Review existing guidance to make sure it fully supports the change:
- [Designing page update](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/issues/1084)

**Comment by janchild** [comment]
My recommendation is to have a shorter Slack message that links to an updated `Expressive now in Carbon` page. 

[Work in progress](https://ibm.ent.box.com/notes/860852055370) can be seen here.
