### ISSUE TITLE
[Locale selector] Design clean up to address inconsistencies 

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#6266]
### Problem
Locale selector is one of the "first borns" and contains some inconsistencies compared to the standard the team later established. Example of inconsistency: 

- Not using card group
- Search bar using expressive 
- Label text size 

### Task

Design a more consistent version of Locale selector, so it's more integrated with the rest of the library. Not expecting a complete redesign, but more like a re-visit and clean up. 

1. Use `card group` & `link list` if make sense
2. Consider styling changes since the Expressive theme sunset, and explore bettering options 

### Box
[Link to box folder](https://ibm.ent.box.com/folder/82255256134?s=nwy0fyiw6mu3qwd3p882pnqmit93rfa5)

#### Acceptance criteria 

- [x] A Sketch file is created or updated with the `?component name?` design and specs
- [x] Create a Box folder for the `?component name?` (if not already there)
- [x] The design specs and pdf version are added to the Box folder 
- [x] Play back with team!

**Comment by shixiedesign** [comment]
Should we go in with a redesign instead and align to use Card group?

**Comment by oliviaflory** [comment]
> Should we go in with a redesign instead and align to use Card group?

Whatever you think is best! This issue was to align the specs with the removal of expressive theme dev work. 

I'm not positive if we would finish re-design and dev before expressive theme removal launch, but maybe that's fine?
