### ISSUE TITLE
Web Component:  Card section - carousel MVP component

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/carbon-for-ibm-dotcom#630]
#### User Story

> As an:

IBM.com customer

> I need to:

quickly look through a series of content (e.g. images, videos, text and more)

> so that I can:

make a decision or get on with the rest of my day

#### Additional information

 - Examples
   - [Northstar v18 Carousel](https://www.ibm.com/standards/web/v18/design/carousels/)
   - [Bootstrap Carousel](https://getbootstrap.com/docs/4.0/components/carousel/)
- [Accessible carousel concepts](https://www.w3.org/WAI/tutorials/carousels/)
- [Coded prototype based on lightbox media viewer needs](https://github.com/photodow/ibm-dotcom-library/wiki/%5Bfs%5D-Carousel)
- The design and functional specs review has been included in the Oct 19 Engineering meeting for review and dev sizing.

##### In context of the lightbox (image viewer)
<img src="https://user-images.githubusercontent.com/3793636/68248952-778e8a00-ffe3-11e9-825c-af79c38b7525.png" width="400px" />

##### In context of the logo grid
<img src="https://user-images.githubusercontent.com/3793636/68249281-1dda8f80-ffe4-11e9-9a46-5d48885bb290.png" width="400px" />

#### Acceptance criteria
 - [ ] Meets the needs of the [lightbox (image viewer)](https://github.com/carbon-design-system/ibm-dotcom-library/issues/328)
 - [ ] Meets the needs of the [logo grid](https://github.com/carbon-design-system/ibm-dotcom-library/issues/408)
 - [ ] Scaleable across small content and large content
 - [ ] Scaleable across different layouts
    (e.g. we might need 6 across for the lightbox (image viewer), but the logo grid we might need 3 rows of 3)
 - [ ] Handles a single slide
 - [ ] Handles a large number of slides (10 or more for now)
 - [ ] Cycles through one slide of content at a time (will we need auto slides?)
 - [ ] Jump between slides (e.g. slide 1 to slide 4)
 - [ ] Accessible and mobile friendly

**Comment by RobertaJHahn** [comment]
This component is not needed immediately by adopters.  Moving to backlog to be scheduled in the future.

**Comment by RobertaJHahn** [comment]
This component has moved to a higher priority because of the Hybrid Cloud organization needs this component.  The DDS Design squad is doing research on potential designs.   This work is managed under issue #124 on the Ideation board.  https://app.zenhub.com/workspaces/digital-design-ideation-5e8e2526b7bb5c920432c971/issues/carbon-design-system/digital-design-ideation/124

Added the Hybrid Cloud label.

**Comment by RobertaJHahn** [comment]
James will work separately with Akira to review the func specs.  Will update the epic status when complete.

**Comment by photodow** [comment]
Created two new components, and updated an existing one.

- [Content section](https://ibm.ent.box.com/file/677504365574)
- [Carousel](https://ibm.ent.box.com/file/743532459763)
- [Card section — carousel](https://ibm.ent.box.com/folder/126468155543)
