### ISSUE TITLE
Project Pupa: Adopter As-is Journey Map

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-dotcom#6300]
### Objective:

We will create an Adopter As-is Journey Map to spot pain points and solution opportunities based on interview findings.

### Tasks:

- [ ] Set up the Mural board for the As-is Journey Map creation.
- [ ] Schedule work sessions to work on the maps together as a team based on the findings synthesizing from the interviews. Note: Synthesizing work will be recorded in task issue X.

### Acceptance criteria (The meaning of "Done")

- [ ] Have journey map ready to share with the team.
- [ ] Create task issue for the next step.

**Comment by JennySanchez** [comment]
Issue moved to [carbon-design-system/carbon-for-ibm-dotcom-website #1034](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/issues/1034) via [**ZenHub**](https://www.zenhub.com/)
