### ISSUE TITLE
IBM.com spatial model and screen region study

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/carbon-for-ibm-dotcom#6439]
### Objectives
- As multiple popups, overlays, and banners are added to IBM.com, we need a guidelines around where what should be fitted to form a consistent and logical mental model. Eg) User conversation interstitials such as UMX and Site feedback are in the lower right corner, while notifications are in the lower middle, and banners are at the top. (this is just an example).

### Tasks
- [ ] Collect potential interstitial components on IBM.com and put together a list
- [ ] Study different models
- [ ] Define different spaces for different components

### THings to consider
- What are the mental model and the logical backing of it? Eg) Why should the Let's talk button positioned in the lower right corner?
- Known interstitial components of IBM.com
   - UMX
   - Site feedback
   - Banner (COVID-19 at the top is current example)
   - Locale change notification
   - Other potential generic notifications
   - System alert and announcements (the yellow banner of v18)
