### ISSUE TITLE
Support content audit

### ISSUE THREAD

**Issue by janchild** [carbon-design-system/carbon-for-ibm-dotcom#6636]
Continued work building the robot army... this epic covers the dev and design work required for creating a bot that will answer first-level questions in our #carbon-for-ibm-dotcom Slack channel. 

**Additional Information**
- Found a bot that might work OOTB: https://pages.github.ibm.com/power-ups/support-channel-bot-pages/#get-started

Work to do:
- [ ] Research with the Taasbot crew
- [ ] Assess initial Slack audit from interns
- [ ] Work with Bob Moore (IBM Research) conversational scientist to structure conversations
- [ ] Find automated system for extracting data from Slack channel 
- [ ] Determine how to use AI to train the bot for continual refinement and improvement
