### ISSUE TITLE
[Web components]: create remaining React wrapper components

### ISSUE THREAD

**Issue by kennylam** [carbon-design-system/carbon-for-ibm-dotcom#8602]
#### User Story

> As a `[user role below]`:
an adopter of Carbon for ibm.com

> I need to:
have access to more React wrapper components

> so that I can:
continue to author the most complete experience for IBM.com users.

#### Acceptance criteria
- [ ] Create codesandbox example under `/packages/web-components/examples/codesandbox/components-react` and include in README
- [ ] Use the [Visual QA checklist](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/wiki/Definition-of-done-(Visual-QA-checklist)) to verify design quality
- [ ] If a design is provided, the Designer is included as a Reviewer in the Pull Request
