### ISSUE TITLE
[Content item horizontal] review

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#9298]
### The Problem

Content item horizontal and all subsequent variants (Content item horizontal with media, with featured media) use a 10 column grid layout which breaks the 2x grid usage of IDL guidelines.

### User story

Review the design specs of Content item horizontal and all variants to evaluate the component's usage of the grid. 

### Tasks
- Explore what the component will look like using 8 and 12 columns of the grid at all breakpoints
- Mock up the 8 and 12 column layouts on a page template, see Watson Orchestrate
   - Need to consider implications with Content block + larger content block type
- Review with Carbon team
- Is this considered a breaking change?
- Compare with Gatsby [Expressive list container](https://gatsby.carbondesignsystem.com/components/ExpressiveListContainer)

### Acceptance criteria
- [x] Review with Carbon team
- [x] Review with Mike
- [x] New specs created
- [x] Show to AEM team

**Comment by oliviaflory** [comment]
### Spec file
[Figma](https://www.figma.com/file/Cj5ms1cNwHDcfNidRcNpED/content-item-horizontal?node-id=1%3A3956)
