### ISSUE TITLE
[Lead space] design research

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#9663]
### User story 

As a Carbon for IBM.com Designer I need to review the lead space and background media specs so that I can understand how the lead space is constructed and identify the gaps in documentation for adopters.

#### Tasks

- [x] Review the Lead space, Background media design specs, and both functional specs.
- [x] Talk with Dev team about how it's working
- [x] Determine if we need to make changes
- [x] Determine where to update documentation to make it more clear for adopters.

**[Design research findings - Figma](https://www.figma.com/file/53BjpeiZqb34xM4QeZSjfs/Lead-space-design-research?node-id=0%3A1&t=565F9X8gvuVu6JvB-1)**

### Additional Information
- **See the epic (#?epic issue?) for the overarching descriptions of the work.**
- [Lead space Figma import](https://www.figma.com/file/qUf86S5SSxf8WuLZ638oqa/Layout-component--lead-space--left-aligned--design-specs--v2.1?node-id=5%3A20266&t=00FnmZEvjoS03Rlk-1)
- [Lead space Func specs](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Lead-space)
- [Background media Figma import](https://www.figma.com/file/kgBA21f28d0qTr8b0Rdbv3/UI-component--background-media--design-specs--v1.1?node-id=1%3A3112&t=RuH3CxVdVPypo7ra-1)
- [Background media Func specs](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Background-media)

#### Acceptance Criteria
- [x] Research findings are shared with Jeannie & Olivia
- [x] We agree on next steps for design study

**Comment by oliviaflory** [comment]
Medium breakpoint
Too big to not do ANY imagery, but messes with the type.
- Option for low-contrast background image (platform reference)
- Cloud lead space – should move complex image below 



**Images**
- Could small and medium drop the image?
- Adopters need to know that they can swap the image size for medium and small.
- Jeannie: could we add a dot-grid for users to be there by default? 
- Option for full bleed image (AEM lead space generative art)
- Option for 8 column image (Cloud)

**Additional research**
Gatsby lead space audit
- Gatsby sites have left nav! 
   - Column alignment
- CTAs
- Sub text

**Comment by RichKummer** [comment]
**[Figma file](https://www.figma.com/file/53BjpeiZqb34xM4QeZSjfs/Lead-space-design-research?node-id=0%3A1&t=sAuzi3zHEHAFIQTp-1)**

## Research

### Design specs vs live code
- When in the @md breakpoint, all size variants should drop the image below the copy to match the specs. Currently, they maintain the lock up used for the desktop sizes.
- #5891 states that the @md image should be 16x9 and drop below the header text + buttons.

### Cloud lead space variant
- Would need to make gradient optional
- Would need a study on the 8-column image
- Need to consider color tokens, texture, types of images, etc.

### Func specs
- Specs for both `lead space` and `background media` are bare bones. 
- For `background media`, need more dependencies, auto-playing infor for video. Perhaps file type table.
- For `lead space`, should indicate orientation change on @md and @sm, table for different size variants, table for navigation options (breadcrumbs, etc.)

### Guidance website
- Consider adding a `background media` page? This might not be needed, it's usually used on its own
- Add a section to `lead space` page to discuss preparing assets, including for different breakpoints.
- Include info on Kaltura and how to submit videos. Where can designers find assets - DAM, etc?
