### ISSUE TITLE
[web-components]: prevent custom element registry errors

### ISSUE THREAD

**Issue by jkaeser** [carbon-design-system/carbon-for-ibm-dotcom#9940]
## Problem

As seen in issues like #9330, extending from classes that have used the `@customElement` decorator from the LitElement library can cause errors like the following:

```
Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "dds-button-expressive" has already been used with this registry
```

This is because the decorator calls `customElements.define()` using the provided name string. Extending these classes causes namespace collisions when that method is called multiple times.

## Proposed Resolution
Separate component class definition and `customElements` registrations by adopting a base class model, where the component behaviors are authored in the base class (e.g. `DDSButtonExpressiveBase`), and the custom element registration is handled by an extending class. For example:

```js
export class DDSButtonExpressiveBase extends FocusMixin(StableSelectorMixin(LitElement)) {
  ...
}

@customElement(`${ddsPrefix}-button-expressive`)
class DDSButtonExpressive extends DDSButtonExpressiveBase {}

export default DDSButtonExpressive;
```

```
@customElement(`${ddsPrefix}-button-group-item`)
class DDSButtonGroupItem extends DDSButtonExpressiveBase {
}
```

### packages/web-components
- [ ] `class DDSBackgroundMedia extends DDSImage {`
- [ ] `class DDSButtonGroupItem extends DDSButtonExpressive {`
- [ ] `class DDSCalloutLinkWithIcon extends DDSLinkWithIcon {`
- [ ] `class DDSCalloutQuote extends DDSCalloutMixin(DDSQuote) {`
- [ ] `class DDSCalloutWithMediaCopy extends DDSContentBlockCopy {`
- [ ] `class DDSCalloutWithMediaImage extends DDSImage {`
- [ ] `class DDSCalloutWithMediaVideo extends DDSVideoPlayerContainer {`
- [ ] `class DDSCardFooter extends DDSLinkWithIcon {`
- [ ] `class DDSCard extends StableSelectorMixin(BXLink) {`
- [ ] `class DDSImageLogo extends DDSImage {`
- [ ] `class DDSCardGroupCardLinkItem extends DDSCardLinkCTA {`
- [ ] `class DDSCardGroupItem extends DDSCardCTA {`
- [ ] `class DDSCardInCardImage extends DDSImage {`
- [ ] `class DDSCardInCard extends StableSelectorMixin(DDSCardCTA) {`
- [ ] `class DDSCardLinkHeading extends DDSCardHeading {`
- [ ] `class DDSCardLink extends DDSCard {`
- [ ] `class DDSCardSectionCarousel extends DDSContentSection {`
- [ ] `class DDSCardSectionImages extends StableSelectorMixin(DDSContentSection) {`
- [ ] `class DDSCardSectionOffset extends StableSelectorMixin(DDSContentBlock) {`
- [ ] `class DDSCardSectionSimple extends StableSelectorMixin(DDSContentSection) {`
- [ ] `class DDSContentBlockCopy extends StableSelectorMixin(DDSMarkdown) {`
- [ ] `class DDSContentBlockCardStatic extends StableSelectorMixin(DDSContentBlock) {`
- [ ] `class DDSContentBlockCards extends StableSelectorMixin(DDSContentBlock) {`
- [ ] `class DDSContentBlockHeadlinesItem extends StableSelectorMixin(DDSContentItem) {`
- [ ] `class DDSContentBlockHeadlines extends StableSelectorMixin(DDSContentBlock) {`
- [ ] `class DDSContentBlockHorizontal extends DDSContentGroup {`
- [ ] `class DDSContentBlockMediaContent extends StableSelectorMixin(DDSContentGroup) {`
- [ ] `class DDSContentBlockMedia extends DDSContentBlock {`
- [ ] `class DDSContentBlockMixed extends DDSContentBlock {`
- [ ] `class DDSContentBlockSegmented extends DDSContentBlock {`
- [ ] `class DDSContentBlockSimple extends StableSelectorMixin(DDSContentBlock) {`
- [ ] `class DDSContentGroupCopy extends StableSelectorMixin(DDSMarkdown) {`
- [ ] `class DDSContentGroup extends StableSelectorMixin(DDSContentBlock) {`
- [ ] `class DDSContentGroupBanner extends StableSelectorMixin(DDSContentGroup) {`
- [ ] `class DDSContentGroupCardsItem extends StableSelectorMixin(DDSCard) {`
- [ ] `class DDSContentGroupCards extends DDSContentGroup {`
- [ ] `class DDSContentGroupHorizontal extends DDSContentBlockHorizontal {`
- [ ] `class DDSContentGroupPictograms extends DDSContentGroup {`
- [ ] `class DDSContentGroupSimple extends StableSelectorMixin(DDSContentGroup) {`
- [ ] `class DDSContentItemCopy extends StableSelectorMixin(DDSMarkdown) {`
- [ ] `class DDSContentItemHorizontalMediaFeatured extends DDSContentItem {`
- [ ] `class DDSContentItemHorizontalMediaVideo extends DDSVideoPlayerContainer {`
- [ ] `class DDSContentItemHorizontalMedia extends HostListenerMixin(DDSContentItem) {`
- [ ] `class DDSContentItemHorizontal extends DDSContentItem {`
- [ ] `class DDSContentSectionCopy extends StableSelectorMixin(DDSMarkdown) {`
- [ ] `class DDSButtonCTA extends VideoCTAMixin(CTAMixin(DDSButtonGroupItem)) {`
- [ ] `class DDSCardCTAFooter extends VideoCTAMixin(CTAMixin(DDSCardFooter)) {`
- [ ] `class DDSCardCTAImage extends DDSImage {`
- [ ] `class DDSCardCTA extends VideoCTAMixin(CTAMixin(DDSCard)) {`
- [ ] `class DDSCardLinkCTA extends VideoCTAMixin(CTAMixin(DDSCardLink)) {`
- [ ] `class DDSFeatureCTA extends VideoCTAMixin(CTAMixin(DDSFeatureCard)) {`
- [ ] `class DDSLinkListItemCardCTA extends DDSCardCTA {`
- [ ] `class DDSLinkListItemCTA extends DDSTextCTA {`
- [ ] `class DDSTextCTA extends VideoCTAMixin(CTAMixin(DDSLinkWithIcon)) {`
- [ ] `class DDSCTABlockItem extends StableSelectorMixin(DDSContentItem) {`
- [ ] `class DDSCTABlock extends StableSelectorMixin(DDSContentBlock) {`
- [ ] `class DDSCTASection extends StableSelectorMixin(DDSContentSection) {`
- [ ] `class DDSExpressiveModalBody extends StableSelectorMixin(BXModalBody) {`
- [ ] `class DDSExpressiveModalFooter extends StableSelectorMixin(BXModalFooter) {`
- [ ] `class DDSExpressiveModalHeader extends StableSelectorMixin(BXModalHeader) {`
- [ ] `class DDSExpressiveModalHeading extends StableSelectorMixin(BXModalHeading) {`
- [ ] `class DDSFeatureCardFooter extends DDSCardFooter {`
- [ ] `class DDSFeatureCard extends StableSelectorMixin(DDSCard) {`
- [ ] `class DDSFeatureCardBlockLargeFooter extends DDSFeatureCardFooter {`
- [ ] `class DDSFeatureCardBlockLarge extends StableSelectorMixin(DDSFeatureCard) {`
- [ ] `class DDSFeatureCardBlockMedium extends DDSFeatureCard {`
- [ ] `class DDSFeatureSectionCardLink extends DDSCardCTA {`
- [ ] `class DDSFeatureSection extends StableSelectorMixin(DDSFeatureCard) {`
- [ ] `class DDSFilterGroupItem extends StableSelectorMixin(BXAccordionItem) {`
- [ ] `class DDSFilterGroup extends StableSelectorMixin(BXAccordion) {`
- [ ] `class DDSFilterModalButton extends StableSelectorMixin(BXModalFooterButton) {`
- [ ] `class DDSFilterModalFooter extends StableSelectorMixin(BXModalFooter) {`
- [ ] `class DDSFilterModalHeading extends StableSelectorMixin(BXModalHeading) {`
- [ ] `class DDSComboBox extends DDSDropdown {`
- [ ] `class DDSDropdown extends BXDropdown {`
- [ ] `class DDSFooterNavItem extends BXLink {`
- [ ] `class DDSLanguageSelectorDesktop extends HostListenerMixin(DDSComboBox) {`
- [ ] `class DDSLanguageSelectorMobile extends BXSelect {`
- [ ] `class DDSLegalNavItem extends DDSFooterNavItem {`
- [ ] `class DDSBreadcrumbItem extends StableSelectorMixin(BXBreadcrumbItem) {`
- [ ] `class DDSBreadcrumbLink extends StableSelectorMixin(BXBreadcrumbLink) {`
- [ ] `class DDSBreadcrumb extends StableSelectorMixin(BXBreadcrumb) {`
- [ ] `class DDSLeadspaceImage extends StableSelectorMixin(DDSImage) {`
- [ ] `class DDSLeadSpaceBlockContent extends DDSContentBlock {`
- [ ] `class DDSLeadSpaceBlockCTA extends StableSelectorMixin(DDSButtonGroup) {`
- [ ] `class DDSLeavingIbmModalBody extends StableSelectorMixin(BXModalBody) {`
- [ ] `class DDSLeavingIbmModalHeading extends StableSelectorMixin(BXModalHeading) {`
- [ ] `class DDSLeavingIbmModal extends StableSelectorMixin(BXModal) {`
- [ ] `class DDSLightboxImageViewer extends DDSLightboxMediaViewerBody {`
- [ ] `class DDSLightboxMediaViewer extends DDSLightboxMediaViewerBody {`
- [ ] `class DDSLightboxVideoPlayer extends DDSLightboxMediaViewerBody {`
- [ ] `class DDSLinkListItem extends DDSCardLink {`
- [ ] `class DDSLinkListItem extends DDSLinkWithIcon {`
- [ ] `class DDSLinkListSection extends StableSelectorMixin(DDSContentSection) {`
- [ ] `class DDSLinkWithIcon extends StableSelectorMixin(BXLink) {`
- [ ] `class DDSLocaleItem extends BXLink {`
- [ ] `class DDSLocaleModal extends DDSExpressiveModal {`
- [ ] `class DDSRegionItem extends BXLink {`
- [ ] `class DDSLogoGridItem extends StableSelectorMixin(DDSImage) {`
- [ ] `class DDSLogoGridLink extends StableSelectorMixin(DDSCardLink) {`
- [ ] `class DDSLogoGrid extends StableSelectorMixin(DDSContentBlock) {`
- [ ] `class DDSCloudButtonCTA extends DDSButtonExpressive {`
- [ ] `class DDSCloudLeftNavItem extends BXSideNavLink {`
- [ ] `class DDSCloudMastheadComposite extends DDSMastheadComposite {`
- [ ] `class DDSCloudMastheadGlobalBar extends DDSMastheadGlobalBar {`
- [ ] `class DDSCloudMastheadProfile extends DDSMastheadProfile {`
- [ ] `class DDSCloudMegaMenuCateoryLink extends BXLink {`
- [ ] `class DDSCloudMegaMenuLeftNavigation extends DDSMegaMenuRightNavigation {`
- [ ] `class DDSCloudMegaMenuRightNavigation extends DDSMegaMenuLeftNavigation {`
- [ ] `class DDSCloudMegaMenuTab extends BXTab {`
- [ ] `class DDSCloudMegaMenuTabs extends BXTabs {`
- [ ] `class DDSCloudMegaMenu extends DDSMegaMenu {`
- [ ] `class DDSCloudTopNavName extends DDSTopNavName {`
- [ ] `class DDSLeftNavItem extends BXSideNavLink {`
- [ ] `class DDSLeftNavMenuItem extends BXSideNavMenuItem {`
- [ ] `class DDSLeftNavName extends BXHeaderName {`
- [ ] `class DDSLeftNav extends StableSelectorMixin(BXSideNav) {`
- [ ] `class DDSMastheadMenuButton extends HostListenerMixin(BXHeaderMenuButton) {`
- [ ] `class DDSMastheadProfileItem extends BXHeaderMenuItem {`
- [ ] `class DDSMegaMenuCateoryLink extends BXLink {`
- [ ] `class DDSMegaMenuLinkWithIcon extends BXLink {`
- [ ] `class DDSMegaMenuTopNavMenu extends DDSTopNavMenu {`
- [ ] `class DDSSkipToContent extends BXSkipToContent {`
- [ ] `class DDSTopNavItem extends BXHeaderNavItem {`
- [ ] `class DDSTopNavL1 extends DDSTopNav {`
- [ ] `class DDSTopNavMenuItem extends BXHeaderMenuItem {`
- [ ] `class DDSTopNavMenu extends BXHeaderMenu {`
- [ ] `class DDSTopNavName extends DDSLeftNavName {`
- [ ] `class DDSTopNav extends StableSelectorMixin(HostListenerMixin(BXHeaderNav)) {`
- [ ] `class DDSPictogramItem extends StableSelectorMixin(DDSContentItem) {`
- [ ] `class DDSPricingTableBody extends StableSelectorMixin(DDSStructuredListBody) {`
- [ ] `class DDSPricingTableGroup extends StableSelectorMixin(DDSStructuredListGroup) {`
- [ ] `class DDSPricingTableHead extends StableSelectorMixin(DDSStructuredListHead) {`
- [ ] `class DDSPricingTableHeaderCellCta extends StableSelectorMixin(DDSButtonCTA) {`
- [ ] `class DDSPricingTableHeaderCellTag extends StableSelectorMixin(DDSTagLink) {`
- [ ] `class DDSPricingTableRow extends StableSelectorMixin(DDSStructuredListRow) {`
- [ ] `class DDSQuoteLinkWithIcon extends DDSLinkWithIcon {`
- [ ] `class DDSSearch extends BXSearch {`
- [ ] `class DDSScopedSearchDropdownMobile extends BXSelect {`
- [ ] `class DDSScopedSearchDropdown extends DDSDropdown {`
- [ ] `class DDSStructuredListBody extends BXStructuredListBody {`
- [ ] `class DDSStructuredListCell extends BXStructuredListCell {`
- [ ] `class DDSStructuredListHead extends BXStructuredListHead {`
- [ ] `class DDSStructuredListHeaderCell extends BXStructuredListHeaderCell {`
- [ ] `class DDSStructuredListHeaderRow extends BXStructuredListHeaderRow {`
- [ ] `class DDSStructuredListRow extends BXStructuredListRow {`
- [ ] `class DDSTabsExtendedMedia extends DDSTabsExtended {`
- [ ] `class DDSUniversalBannerCopy extends StableSelectorMixin(DDSMarkdown) {`
- [ ] `class DDSUniversalBannerImage extends DDSImage {`

### packages/carbon-web-components

- [ ] `class BXBreadcrumbLink extends BXLink {`
- [ ] `class BXBreadcrumbOverflowMenu extends BXOverflowMenu {`
- [ ] `class BXButtonSkeleton extends BXButton {`
- [ ] `class BXComboBoxItem extends BXDropdownItem {`
- [ ] `class BXComboBox extends BXDropdown {`
- [ ] `class BXTableCellSkeleton extends BXTableCell {`
- [ ] `class BXTableExpandRow extends HostListenerMixin(BXTableRow) {`
- [ ] `class BXTableHeaderCellSkeleton extends BXTableCell {}`
- [ ] `class BXTableHeaderExpandRow extends BXTableExpandRow {`
- [ ] `class BXTableHeaderRow extends BXTableRow {`
- [ ] `class BXTableToolbarSearch extends HostListenerMixin(BXSearch) {`
- [ ] `class BXOrderedList extends BXUnorderedList {`
- [ ] `class BXModalFooterButton extends BXButton {`
- [ ] `class BXMultiSelectItem extends BXDropdownItem {`
- [ ] `class BXMultiSelect extends BXDropdown {`
- [ ] `class BXToastNotification extends BXInlineNotification {`
- [ ] `class BXNumberInput extends BXInput {`
- [ ] `class BXOverflowMenuBody extends BXFloatingMenu {`
- [ ] `class RadioButtonDelegate implements ManagedRadioButtonDelegate {`
- [ ] `class BXTab extends BXContentSwitcherItem {`
- [ ] `class BXTabs extends HostListenerMixin(BXContentSwitcher) {`
- [ ] `class BXClickableTile extends BXLink {`
- [ ] `class BXRadioTile extends HostListenerMixin(SelectableTile) {`
- [ ] `class BXToggle extends BXCheckbox {`
- [ ] `class BXTooltipBody extends BXFloatingMenu {`
- [ ] `class BXTooltipIcon extends BXTooltipDefintion {`
- [ ] `class BXHeaderMenuItem extends BXHeaderNavItem {}`

**Comment by m4olivei** [comment]
Couple questions. First, is it only when multiple component extending the same base are defined on the same page that this turns up?

Second, @jkaeser, can you share the methodology for finding all of the affected components? Is there a way to search for all affected components to come up with the list here? Was it a manual process of iterating through every component under `packages/[carbon-]web-components` and checking if each extended some other non-base class w/ potential for collision? Or does this list represent every component? Going foward, is there a heuristic for when a component requires a base component,  component pair?

**Comment by jkaeser** [comment]
@m4olivei 

1. It happens whenever the same unique component name is registered multiple times on a given webpage. There's [a babel plugin](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/packages/web-components/tools/babel-plugin-undef-custom-elements.js) that works around the issue within this the `web-components` package, but this is a workaround; it doesn't save us when _different_ libraries attempt register the same name. This can happen for a number of reasons, but some real world examples are: 
   1. a single page loading multiple built versions of C4IBM
   2. a page using C4IBM and C4AEM where both include elements that extend from a common parent element (such as `DDSButton` and `CAEMButton` both extending from `BXButton`, which would throw the error for `BXButton`)
2. I believe this list shows any component that extends from anything other than `LitElement`. @andy-blum is that right, and do you still have the regex we used to find affected components? As for a heuristic, that's a good question, and I don't have a great answer. It's possible that every component should use this base class model since we can't know for sure which ones somebody will want to extend from in the future.

**Comment by proeung** [comment]
@kennylam @jeffchew We're still blocked on this issue. Does anyone within your team have any bandwidth next week to help pair with us on the remaining work for this issue (https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/9941)? We'd like to get progress moving on this duplicate registry issue as it's blocking our Widget team from adopting the Web Components package into their system.

**Comment by abdonrd** [comment]
Related PR from the lit repository:
- https://github.com/lit/lit/pull/4461
